
BLUEZ_SERVICE_NAME = "org.bluez"
GATT_MANAGER_IFACE = "org.bluez.GattManager1"
DBUS_OM_IFACE =      "org.freedesktop.DBus.ObjectManager"
DBUS_PROP_IFACE =    "org.freedesktop.DBus.Properties"
GATT_SERVICE_IFACE = "org.bluez.GattService1"
GATT_CHRC_IFACE =    "org.bluez.GattCharacteristic1"
GATT_DESC_IFACE =    "org.bluez.GattDescriptor1"

LE_ADVERTISING_MANAGER_IFACE = "org.bluez.LEAdvertisingManager1"
LE_ADVERTISEMENT_IFACE = "org.bluez.LEAdvertisement1"

NOTIFY_TIMEOUT = 5000
BUTTON_COMMAND_ID = "121"
RIGHT_JOYSTICK_COMMAND_ID = "122"
LEFT_JOYSTICK_COMMAND_ID = "123"
OPTION_COMMAND_ID = "124"

OPTION_BUTTON = 1

TOP_DIRECTION = 1
BOTTOM_DIRECTION = 2
LEFT_DIRECTION = 4
RIGHT_DIRECTION = 8
X_BUTTON = 16
SQUARE_BUTTON = 32
CIRCLE_BUTTON = 64
TRIANGLE_BUTTON = 128



